---
outdir: 'simple_large_custom_batchnorm'
data_hyperparams:
  root: '../data/jetid'
  nconst: 8
  feats: "ptetaphi"
  norm: "robust"
  kfolds: 5
  seed: 511

model_type: "sinvariant"
model_hyperparams:
  phi_layers: [32, 32]
  phi_activations: ["relu", "relu"]
  phi_normalizations: ["batch", "batch"]
  rho_layers: [32, 32, 64]
  rho_activations: ["relu", "relu", "leaky_relu"]
  rho_normalizations: ["batch", null, "batch"]
  activ: "relu"
  leaky_relu_alpha: 0.01
  aggreg: "mean"
  aggreg_precision:
    bits: 32
    integer: 16
  output_dim: 5
  nbits: 32

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0029
  optimizer_callbacks:
    early_stopping:
      monitor: "val_categorical_accuracy"
      patience: 7
    lr_decay:
      monitor: "val_categorical_accuracy"
      factor: 0.8
      patience: 4
      min_lr: 0.0001

  # loss: "categorical_crossentropy"
  loss: "softmax_with_crossentropy"
  metrics: ["categorical_accuracy"]
  early_stopping: 7

training_hyperparams:
  batch_size: 256
  epochs: 50
  shuffle: True
  verbose: 2