---
outdir: 'synth_small'
data_hyperparams:
  root: '../data/jetid'
  nconst: 8
  feats: "ptetaphi"
  norm: "robust"
  kfolds: 5
  seed: 511

model_type: "sinvariant"
model_hyperparams:
  phi_layers: [8, 8]
  phi_activations: ["leaky_relu", "relu"]
  phi_normalizations: ["batch", null]
  rho_layers: [16, 16]
  rho_activations: ["leaky_relu", "relu", "leaky_relu"]
  rho_normalizations: ["batch", "batch", null]
  activ: "relu"
  leaky_relu_alpha: 0.01
  aggreg: "mean"
  aggreg_precision:
    bits: 20
    integer: 10
  output_dim: 5

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0029
  optimizer_callbacks:
    early_stopping:
      monitor: "val_categorical_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_categorical_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "softmax_with_crossentropy"
  metrics: ["categorical_accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 256
  epochs: 10
  shuffle: True
  verbose: 2